name: Production Deployment
on:
  push:
    tags: ['v*','!v*-*']
jobs:
  call-deployment:
    uses: iconicompany/iconicactions/.github/workflows/deployment.yml@main
    secrets: inherit
    with:
      WERF_ENV: production
      DOMAIN: iconicompany.ru
