name: Testing Deployment
on:
  push:
    branches: ["main", "master"]
  pull_request:
    types: [labeled, unlabeled, synchronize, closed, reopened]
jobs:
  call-deployment:
    uses: iconicompany/iconicactions/.github/workflows/deployment.yml@main
    secrets: inherit
    with:
      #RUNS_ON: self-hosted
      DOCKER_BUILDKIT: true
      WERF_ENV: testing
      DATABASE_URL: postgres://postgresql01.kube01.icncd.ru
